### ISSUE TITLE
Charcoal multiblocks

### ISSUE THREAD

**Issue by diregarath** [BearsDen989-GT/Gregtech-5u-Bears-Den-Edition#16]
@bear989 @e99999 Lets decide how to move forward with charcoal - we can comment on the issue here so we keep track of our thoughts.

**Comment by bear989** [comment]
I can agree with @leagris that the charcoal smelting in a furnace should stay and the charcoal pit igniter sucks ass from .09 so how about we port the primative blast furnace and use those bricks to make a coke oven, option on doing as greg did in GT6 to do multiple operations in on so you dont need to make 16 of the damn things before you get to the pyroluse, witch we need to add as well. should take steel to make the controller since it will be so powerful

**Comment by e99999** [comment]
closing for discussion on #9

**Comment by bear989** [comment]
since you closed the discussion are you making an issue or adding thing to the todo list for it?

**Comment by e99999** [comment]
Bear and I figure just use the Pyrolyse Oven for all your Coke Oven needs - now that Ive ported it. Sure if we want to go back and add a Coke Oven we can, but in terms of issues facing our initial release this is ready to be closed.  

To be clear, there is still the vanilla method of logs->charcoal. The Pyrolyse Oven will just give you bonus charcoal and creosote. It will also preform the duties of a RC coke oven if RC is loaded.

**Comment by diregarath** [comment]
If RC is loaded RC coke oven will still be there too.  Which seems like an ok compromise.
