### ISSUE TITLE
Discussion: Tiered farming multi block

### ISSUE THREAD

**Issue by e99999** [BearsDen989-GT/Gregtech-5u-Bears-Den-Edition#31]
Basic Idea: Instead of writing all the stupid code to make trees and plants grow and harvest in world, the plan is to implement a multi block resembling a hydroponics gardening system instead.

Crazy's idea (which I like a lot) is that the recipes yield would be based on the empty internal space of the multi block. So for example an LV multi block would be 5x5 giving you a 3x3 interior, allowing you to grow one small tree/bush or 9 crops per operation. However an MV or HV multi block that was like 7x7 or 9x9 would allow more material per tree "growth" or more planting space in crop recipes. 

Discussion open on what materials it would take to grow plants and tree, definitely take in water, but should it need air input as well, or fertilizer?

*Recipes would always give saplings/seeds necessary to create a feedback loop.

**Comment by bear989** [comment]
since IC2 is a dependency of GT5 i would say it should take in what you can give a crop matron, water, fertalizer, and weedex. but not require the weedex since most people dont use it and it is a contained structure. if you are going to do size depending on tier then a 3x3x3 isnt large enuff to grow a tree in so only crops in that one, MV or larger for trees. should take seed bags and work off the ic2 crop system so you can use it rather than a harvester if you want, you should have air vents as part of the MB structure.

**Comment by e99999** [comment]
You could grow trees in 3x3 it would just be a bush size. 2 vertical logs with leaf blocks on all sides of the top log.

**Comment by e99999** [comment]
closing ideas, restricting to bugs
