### ISSUE TITLE
Discussion: banded iron with calcite in BR gives different byproducts

### ISSUE THREAD

**Issue by e99999** [BearsDen989-GT/Gregtech-5u-Bears-Den-Edition#47]
better way of processing than electrolyzing,

clay as byproduct instead of small banded iron dust.

dust should have BR recipe and be the best method.

you should get by products from the processing then the final stage be BR. not BR the ore.

-Bear

**Comment by bear989** [comment]
ok so here is the idea, greg has had this calcite iron ore thing since GT2 and I think as the mod has advanced that just got left behind. Banded iron is iron and clay in layers so why not make the byproduct tiny piles of clay rather than more banded iron. also I think the electrolyzer recipe should then give for the 5 banded iron dust 2 iron and 3 silicon dioxide or 2 and 2 with 1000L of O, then as a altrnative you could use sone calcite and 5 banded iron to give 3 iron and 1 silicon ingot in the blast furnace,

**Comment by e99999** [comment]
added
