### ISSUE TITLE
add pebble bed reactor

### ISSUE THREAD

**Issue by bear989** [BearsDen989-GT/Gregtech-5u-Bears-Den-Edition#88]
fluid input D. water or Coolent
item input uranium or thorium rounds or add a pebble pebble = 1 nugget in size
item output would be spent pellets,  pellets that would then be centrifuged for thorium/uranium and lead/plutonium and small amounts of radon
plutonium pellets would be more power but requires coolent only, spent pellets uranium no radon
thorium would be long life but low power 
uranium would be average life and power
Plutonium would be short life large power

**Comment by netmc** [comment]
My thoughts on something like this since it is an alternative to the IC2 nuclear reactor that requires sitting around a planner or looking through old forum posts for a stable reactor plan is that it is completely hands-off.  It requires no planning at all.  Simply feed it fuel and water/coolant and it makes power and gives you the output.  Since this is also hands-off, you can't turn it off except by cutting off the fuel supply.  It works similar to the magic energy converter that "burns" magic items.  You get a fixed amount of power per tick until the stored energy in the item is depleted.  I think that this is a fair trade-off for having a fairly simple nuclear reactor.

**Comment by e99999** [comment]
closing ideas, restricting to bugs
